Repository frenck/action-home-assistant, pull requests merged in 2021-01, with the labels that each got.

#2 Add Release Tracker to fix versions
  .github/workflows/release-tracker.yaml
  README.md
Labels: bugfix

#3 Allow manual dispatching test workflow
  .github/workflows/test.yaml
Labels: ci

#4 Add real world examples
  README.md
Labels: documentation

#5 Simply additional tags
  .github/workflows/additional-tags.yaml
  .github/workflows/lint.yaml
  .github/workflows/release-tracker.yaml
Labels: ci

#6 Trigger additional tags on release and manual
  .github/workflows/additional-tags.yaml
Labels: ci

#7 Collection of small documentation tweaks
  README.md
Labels: documentation

#10 Tweaks to naming in Linter CI
  .github/workflows/lint.yaml
Labels: ci

#11 Fix maintenance vs chore label issue
  .github/labels.yml
  .github/release-drafter.yml
Labels: maintenance

#13 ✨ Add Klaas Schouten's repo to real-world examples
  README.md
Labels: documentation

#15 Add /me to real world examples
  README.md
Labels: documentation
